### ISSUE TITLE
(1.12.2) Broken GUI with Skyblock mod 

### ISSUE THREAD

**Issue by Rafii2198** [CreativeMD/OnlinePictureFrame#11]
When you have Skyblock mod:

- Whenever you look at the Skyblok but there are blocks in the way, the buttons will be invisible:
  ![2017-11-22_20 58 10](https://user-images.githubusercontent.com/26695327/33147633-c3345838-cfc8-11e7-9ffd-6abce2ccf67a.png)
- Whenever you look directly at the Skyblok the buttons will be seen but only those ones on Skyblock:
  ![2017-11-22_20 58 32](https://user-images.githubusercontent.com/26695327/33147658-d29c8584-cfc8-11e7-8e8f-481fc3e65be5.png)
- Whenever you see only Skyblock everything is right:
   ![2017-11-22_20 58 50](https://user-images.githubusercontent.com/26695327/33147687-f48cbf38-cfc8-11e7-9e3f-e2d47d5c571f.png)

But all the buttons work even if they aren't seeable

**Comment by CreativeMD** [comment]
Which skyblock mod? Ex Nihilo?

**Comment by Rafii2198** [comment]
No, the mod is called "Skyblock" it adds a block called "Skyblock" and it makes you see only sky through this(unless you give it redstone signal).

**Comment by CreativeMD** [comment]
Yes, but there is no mod called "Skyblock" (at least i couldn't find it), so could you send me a link?

**Comment by Rafii2198** [comment]
It is called "Skyblocks" with "s" at the end. I'm sorry but I think one letter makes no change https://minecraft.curseforge.com/projects/skyblocks

**Comment by CreativeMD** [comment]
Honestly i have no idea how to fix it, might be a good idea to contact the author of skyblocks as well.

**Comment by Rafii2198** [comment]
Ok, I will do it then.
