### ISSUE TITLE
image render under ShaderMod issues

### ISSUE THREAD

**Issue by PorPit** [CreativeMD/OnlinePictureFrame#12]
version:1.10.2
shadermod:OptiFine_1.10.2_HD_U_E3
shader:SEUS v11.0

when i use some shader(like SEUS V11),some time the image was breaking
look like this ↓↓↓↓↓↓
![2017-12-15_13 27 17](https://user-images.githubusercontent.com/18258014/34028078-bd499f70-e19b-11e7-9d32-6f8d86d55ae6.png)
this is very weird;
do you know what reason with that?

**Comment by CreativeMD** [comment]
I know this issue, but i can't do anything about it. Maybe try to use a different shader or update to the newer minecraft versions :(
