### ISSUE TITLE
[Suggestion] Client Side Image Caching

### ISSUE THREAD

**Issue by kreezxil** [CreativeMD/OnlinePictureFrame#13]
So I like how the mod is and based on our previous conversations I'm totally in agreement with it. But some of my players have noticed that from time to time they have to relog/restart their clients to get pictures back that have vanished. I think it is due to an issue in communicating with the place where the images are hosted.

I'd like to have an option or ability of the mod that after it loads an image for a frame that the image is cache on the client computer. Then when the sign is encountered again if the url to the image hasn't changed the cached version is loaded instead of reaching out to the internet again.

Granted I don't really know if you mod caches the images or behaves in the way I suggest, but i sure feels like it doesn't.

**Comment by CreativeMD** [comment]
Hey there,
I read your post about 100 times, but never found the time to get to it, sorry for that.

Would a clear cache button solve the issue?

**Comment by kreezxil** [comment]
I don't know, you took so long that I moved on. 

Explain to me how your cache works now, a flowchart would help. It seems to me if you were caching the image after fetching it from the url. That when the player is viewing the sign, whether it be immediately or 4 hours later, if the url is the same as the last time that it should have no issue pulling the image out of cache. But somehow that appears broken.

I eventually experienced the issue and sadly had to remove the mod from my pack. :(

**Comment by CreativeMD** [comment]
Images downloaded from the internet will be saved on your hard drive. Once they need to be loaded OPF will check whether the website has been modified since then or not. Depending on the result it will either load the picture from your hard drive (if it's still up to date) or download it again.
