### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Murbis1** [CreativeMD/OnlinePictureFrame#14]
I installed this mod on my Linux Server WITH the core mod for 1.12.2 but it always let my server crash pls fix that

**Comment by CreativeMD** [comment]
I need the crash-report. Otherwise i can't do anything about it.

**Comment by CreativeMD** [comment]
I will close the issue for now. Just reopen this issue if this issue appears again (and please provide a crash-report).

**Comment by Murbis1** [comment]
fixed it :)

**Comment by CreativeMD** [comment]
That's good to hear.
