### ISSUE TITLE
Question - Support for Transparency

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CreativeMD/OnlinePictureFrame#15]
Hey I was wondering if you could support transparency like this mod
https://minecraft.curseforge.com/projects/signpicture/files/2464981

**Comment by CreativeMD** [comment]
You should be able to do so already. What exactly do you have in mind? Maybe explain your idea further?

**Comment by CreativeMD** [comment]
I will close this issue for now, just reopen it and explain what you mean.

**Comment by P3rf3ctXZer0** [comment]
Oh sorry I thought I sent my response 20 days ago "Oh thanks I didn't realize it supported transparency."
