### ISSUE TITLE
Crashes on starting up..

### ISSUE THREAD

**Issue by thedarkrathalos1987** [CreativeMD/OnlinePictureFrame#16]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from OnlinePictureFrame (opframe)

**Comment by CreativeMD** [comment]
Can you send me the entire crash-report?

**Comment by CreativeMD** [comment]
I will close this issue now, if it still persists just reopen this issue and send me the crash-report.
