### ISSUE TITLE
1.12.2 Crash on Startup

### ISSUE THREAD

**Issue by IvoAnic** [CreativeMD/OnlinePictureFrame#20]
[crash-2018-08-20_10.50.13-client.txt](https://github.com/CreativeMD/OnlinePictureFrame/files/2301766/crash-2018-08-20_10.50.13-client.txt)

The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: net.minecraft.block.Block.setRegistryName(Ljava/lang/String;)Lnet/minecraftforge/fml/common/registry/IForgeRegistryEntry;

**Comment by CreativeMD** [comment]
You are using the 1.11.2 for 1.12.2, make sure to download the right one.
