### ISSUE TITLE
Broken GUI (Overlapping elements)

### ISSUE THREAD

**Issue by fandomaniac** [CreativeMD/OnlinePictureFrame#22]
Please see screen-grab below. I'm using Online Picture Frame version 1.4.19 (CreativeCore_v1.9.32) with Forge 1.12.2-14.23.4.2759.

![2018-09-18_12 31](https://user-images.githubusercontent.com/37810246/45703229-a6c50c00-bb41-11e8-93e1-b0237b6d7a17.jpg)

**Comment by CreativeMD** [comment]
Try to update CreativeCore and OnlinePictureFrame to the newest version, this should fix your issue.

**Comment by fandomaniac** [comment]
It's fixed. Thanks.
