### ISSUE TITLE
Y-Axis Align Dropdown Menu selections are: Left, Center and Right, instead of Top, Center and Bottom

### ISSUE THREAD

**Issue by fandomaniac** [CreativeMD/OnlinePictureFrame#23]
Both the X and Y alignment drop-down selections are: Left, Center and Right. 
Shouldn't the Y-axis selections be:  Top, Center and Bottom?

![2018-10-10_17 09](https://user-images.githubusercontent.com/37810246/46766545-4c3a4e00-ccb0-11e8-8593-b9776b8f9cdc.jpg)

**Comment by CreativeMD** [comment]
It is relative to face of the picture, assuming you look directly at it from the front.

**Comment by fandomaniac** [comment]
Relative to the picture, isn't X-axis left and right; and the Y-axis above and below (Top/Bottom)? If I want to top or bottom align the picture, shouldn't there be a "Top" and "Bottom" in the Y-axis? Right now, both X and Y menus list the same Left, Center and Right.

**Comment by CreativeMD** [comment]
You are right, sorry. I fixed it and I will upload a new version soon.
