### ISSUE TITLE
Lost picture in frame

### ISSUE THREAD

**Issue by ExDomino** [CreativeMD/OnlinePictureFrame#27]
Hello,

On our server, sometime we lost pictures in frame. It is like if the frame memorize that an image doesn't exist and then the only way to force it to reload the image is close and reopen the whole game. There is no other way to reload the image.

Version : 1.4.23 for 1.12.2 !

**Comment by CreativeMD** [comment]
The new version 1.4.24 adds it. Sorry that you had to wait so long.

**Comment by ExDomino** [comment]
« Hold shift to reload all pictures »
Which shift? The key to sneak or the left or right shift independant of keybind?
Is it rebindable? Because I'm using shift to jump so if shift also reload frames, it could be a problem.

**Comment by CreativeMD** [comment]
If you click on the reload button while holding shift it will reload all pictures instead of just one.
