### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by Dimensional** [CreativeMD/OnlinePictureFrame#29]
What keyboard keys open the gui? What are the instructions on how to use this mod? The only things I've seen are videos of it just working, but not showing what one must be done to get into the gui, or what items must be crafted.

**Comment by CreativeMD** [comment]
There is just one item the picture frame. I suggest to install a mod like JEI to get the recipe. Just place and right click it to open the gui.
This video might help you: https://www.youtube.com/watch?v=EzabNKA0d64&list=PLlH1j2SwU8QrwD-FXbLrwRfg7ix8NMfGR&index=1

**Comment by Dimensional** [comment]
There's no picture frame item in 1.12.2. And I tried item frame, that also got nothing. I take it this mod, despite saying no uploading the server, requires being installed on the server as well? I was assuming it doesn't because of other mods that do the same thing only needing to be client side.

Edit: I tried this on single player as well, with the mod and it's required core active, and couldn't find anything with picture in the creative menu.

**Comment by CreativeMD** [comment]
Are you sure CreativeCore and OnlinePictureFrame are installed?

EDIT: Of course it has to be installed on server side as well.

**Comment by Dimensional** [comment]
I'm absolutely certain it's installed. I installed it using Twitch, so it made sure CreativeCore dependency was installed too, and it should have worked in single player mode as well. I even reinstalled, and there is no item named Picture Frame.

If there's suppose to be a tab for it in Creative Mode, there isn't any tab, and I don't know where else to locate it in.

Edit: It appeared in JEI/NEI, after looking around, but still not in creative tabs, meaning I can't just spawn it into my inventory.

**Comment by CreativeMD** [comment]
It's in the tab Decorations at the bottom.

**Comment by Dimensional** [comment]
Ah. I reloaded my client a 3rd time and now it's appearing in the creative menu. That's annoying, but might be just my client.
