### ISSUE TITLE
Not Working on Server with other players

### ISSUE THREAD

**Issue by DatTubaMan** [CreativeMD/OnlinePictureFrame#32]
When setting image on frame it does not load for other players and wont allow them to set an image.

**Comment by CreativeMD** [comment]
Are you using local files?

**Comment by DatTubaMan** [comment]
I am using a image hosting site link.

**Comment by CreativeMD** [comment]
Maybe the website is not whitelisted?

**Comment by DatTubaMan** [comment]
I checked that every client has the hosting site is whitelisted.

**Comment by CreativeMD** [comment]
Can you send me the url of the image?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still happens send me the url and reopen this issue.
