### ISSUE TITLE
403 errors should be communicated to the player directly, not just to the console

### ISSUE THREAD

**Issue by DoomRater** [CreativeMD/OnlinePictureFrame#34]
Throwing an exception without telling the player that their picture could not be accessed because of a forbidden access error thrown by the server makes it a lot more confusing trying to figure out why certain pictures load and others don't.  I only noticed because my console was open in the background.

**Comment by CreativeMD** [comment]
Added in the newest version. Thanks for your suggestion! Sorry that it took me so long to respond.
