### ISSUE TITLE
blank poster / does not load the image

### ISSUE THREAD

**Issue by javiburatos** [CreativeMD/OnlinePictureFrame#39]
version 1.7.10
version of mod 1.0
My problem is that when entering any url the poster does not load the image well and only a white background appears

**Comment by CreativeMD** [comment]
Make sure to link the actual image and not the website. You can do that by right clicking the image and hit 'Copy image address'.

**Comment by javiburatos** [comment]
I did it well because on my friends' computer you will see the image, but not from my PC
Could it be for the graphic target?

**Comment by CreativeMD** [comment]
Maybe you have used a local image? You have to upload it somewhere and link it (from the internet). Otherwise other players can't see it.
