### ISSUE TITLE
[Suggestion] Video playback?

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [CreativeMD/OnlinePictureFrame#4]
Great mod.

But it made me start thinking.

It would be nice if we could add videos!

Like adding a twitch stream, or a funny meme video!

Curtis

**Comment by CreativeMD** [comment]
Oh sorry, but this is really complicated to do. I recommend to use [Web Displays](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291044-web-displays-browse-on-the-internet-in-minecraft) instead, but unfortunately it is not updated yet.
