### ISSUE TITLE
A little proposal

### ISSUE THREAD

**Issue by EnterFor** [CreativeMD/OnlinePictureFrame#40]
Version 1.12.2

Can you add a switch to control whether the player can hide the frame?
Some players hide the frame, the administrator can not find the location of the frame
Sorry, my English is poor. I'm Chinese
I like this Mod~

**Comment by CreativeMD** [comment]
I plan to rewrite this mod, I will add some more configuration for it then. Unfortunately I can't tell when I will get to do it.

**Comment by EnterFor** [comment]
oh no

**Comment by CreativeMD** [comment]
I will add this feature request to my todo list and close the issue for now.
