### ISSUE TITLE
relative position/orientation between little picture and other little tiles not preserved when rotated

### ISSUE THREAD

**Issue by carbonox-infernox** [CreativeMD/OnlinePictureFrame#41]
![2020-02-25_21 40 50](https://user-images.githubusercontent.com/27938083/75306614-94133400-5817-11ea-9b67-d82a0a323f6b.png)
little online picture frame was placed on upper left corner of block, and image position was set to right and bottom to align with block. little oak tiles filled in the rest of the frame behind the image for reference.

created multi-tile structure from recipe using workbench (tried fixed and none). when placing this structure, rotating it with the arrow keys does not preserve the relative position or orientation of the image relative to anything else.

version details:
Minecraft: 1.12.2
CreativeCore_v1.9.90_mc1.12.2
LittleTiles_v1.5.0-pre198_mc1.12.2
OnlinePicFrame_v1.4.33_mc1.12.2

**Comment by CreativeMD** [comment]
Yeah, I know it's bugged. I plan to rewrite OnlinePictureFrame, but I don't know when I will get to it.

**Comment by CreativeMD** [comment]
The little online picture frame has been removed. There will be a structure which will have similar functionality, but it's not available yet. I will close the issue nonetheless as it's already removed.
