### ISSUE TITLE
Crash The Game

### ISSUE THREAD

**Issue by SoyJetixXD** [CreativeMD/OnlinePictureFrame#45]
Information:I added the latest version of the mod to my modpack, my game crashes.
![Captura de pantalla (8)](https://user-images.githubusercontent.com/60457424/78203389-72cbe600-745c-11ea-81c5-af3e8630b793.png)
link:https://paste.dimdev.org/qofuqeboqo.mccrash

**Comment by CreativeMD** [comment]
Update CreativeCore.
