### ISSUE TITLE
[Suggestion] Allow a backside view

### ISSUE THREAD

**Issue by D3nnis3n** [CreativeMD/OnlinePictureFrame#46]
SignPicture, while being inferior everywhere else, does also render the image when viewed from the backside, which i do like for a lot of usecases, any chance to get this in OPF? In OPF, when going behind a frame you cannot see the backside of the pic.

**Comment by CreativeMD** [comment]
I'm not really happy with the current state of the mod, I plan to completely rewrite it once 1.5.0 of LittleTiles has been released. Unfortunately that's not soon (probably in about half a year). 
For now the only solution is to place another frame in the opposite direction.
