### ISSUE TITLE
Crash message!

### ISSUE THREAD

**Issue by xombiekilla** [CreativeMD/OnlinePictureFrame#47]
[crash-2020-04-07_03.21.11-client.txt](https://github.com/CreativeMD/OnlinePictureFrame/files/4442585/crash-2020-04-07_03.21.11-client.txt)

I have no idea what's wrong. But This mod is not working right anymore and it always did do just fine before.

**Comment by CreativeMD** [comment]
Update OnlinePictureFrame, that should fix your issue.
