### ISSUE TITLE
Little Online Picture Frame Survival Mode Bug

### ISSUE THREAD

**Issue by patrickclank9** [CreativeMD/OnlinePictureFrame#5]
When trying to create a multi-structure in survival that contains a little online picture frame, it sometimes does not detect the item in my inventory.

After some testing I was able to find out it had to do with orientation:
![2017-03-31_17 06 12](https://cloud.githubusercontent.com/assets/5445944/24573263/14c710ac-1636-11e7-99ec-1df0136423ab.png)
![2017-03-31_17 07 23](https://cloud.githubusercontent.com/assets/5445944/24573264/17b4fbb2-1636-11e7-9bf3-8c65cd5607df.png)
![2017-03-31_17 08 08](https://cloud.githubusercontent.com/assets/5445944/24573265/19710126-1636-11e7-9771-58b88f4be2fb.png)
The gray block is just cobble, but you can see it's recognizing each orientation of the little online picture frame as a separate block.

Thank you for your time.

**Comment by CreativeMD** [comment]
Unfortunately i can't fix it at the moment. I will try to get to it till Saturday.

**Comment by CreativeMD** [comment]
I'm really really sorry, but i was quite busy with other stuff. It is fixed, just download the newest version of LittleTiles and OnlinePictureFrame. Thanks for reporting this issue.

**Comment by patrickclank9** [comment]
Hey, no problem :P Life stuff should always come first. Love what you're doing with the mod and Little Tiles! Keep it up :)
