### ISSUE TITLE
Crashes when i launch

### ISSUE THREAD

**Issue by Mathiousse** [CreativeMD/OnlinePictureFrame#52]
Everytime i launch the game it crashes, tried a LOT of versions of both CreativeCore & Online Picture Frame and still doesn't work

here is the crash log with the two newest versions https://pastebin.com/PWsBAkFZ

**Comment by CreativeMD** [comment]
It's a crash with DoggyTalents. You should update CreativeCore and ItemPhysic (you should also use Full instead of Lite).
