### ISSUE TITLE
Make a real wiki

### ISSUE THREAD

**Issue by rdster** [CreativeMD/OnlinePictureFrame#53]
How about an actual wiki?

Include a how to...permissions...commands...crafting recipe...something....anything.

How do I limit who can use it?

**Comment by rdster** [comment]
How can I limit the size that a player can use?

**Comment by CreativeMD** [comment]
Type in the command /cmdconfig and there you can configure limits. I plan to create a proper permission system, but I'm not sure when I will get to it.
