### ISSUE TITLE
Incorrectly displayed colors.

### ISSUE THREAD

**Issue by Gavuriiru** [CreativeMD/OnlinePictureFrame#56]
Hello! Several of the images I am putting up are showing up with the wrong colors. Can you help me please?

<details>
<summary>Images</summary>

![Thank you](https://user-images.githubusercontent.com/58956441/95655914-07389480-0ae1-11eb-8e3e-1d5589b357de.png )
Originals: 
https://i.imgur.com/amcZ3yI.jpg
https://i.imgur.com/wXrJ09d.jpg
</details>  

(Sorry for my bad english)

**Comment by CreativeMD** [comment]
Which version of the mod are you using? Are there othe rmods installed as well?

**Comment by Gavuriiru** [comment]
1.14.40 and 1.5.0 (with the creative core version released on the same day as the OnlinePictureFrame versions, in both versions the same problem occurs).

Here is a list of the mods that I use:
![image](https://user-images.githubusercontent.com/58956441/95804984-a1aff800-0cda-11eb-9cc8-b92025987a2f.png)
(This world is on a server.)

**Comment by CreativeMD** [comment]
Can you send me the link to the image so I can test it myself?

**Comment by Gavuriiru** [comment]
Of course~:
https://i.imgur.com/amcZ3yI.jpg
https://i.imgur.com/wXrJ09d.jpg

**Comment by CreativeMD** [comment]
Works perfectly fine for me. Does this happen with all pictures? I suspect it's an issue with another mod. Can you try it out with only my mods installed?

**Comment by Gavuriiru** [comment]
This does not happen with all images. The problem started when I moved a frame. The problem persists :(

https://user-images.githubusercontent.com/58956441/95868219-61836080-0d40-11eb-9533-f001a5d21b82.png
(The images on the side are displayed with the correct colors.)

**Comment by CreativeMD** [comment]
Does it happen if only my mods are installed?

**Comment by Gavuriiru** [comment]
yes. for now i'm sending the image in discord and copying the direct link. the colors are right.

**Comment by CreativeMD** [comment]
The issue must be caused by another mod. So the only thing you can do is to figure out what mod is causing this issue. Either send me your modpack or try it yourself (I would prefer that). Just remove half of your mods, test if the issue still persists if not readd some mods again, and so on.

**Comment by Gavuriiru** [comment]
The problem persists, but I think I've already managed to solve the problem by sending the image on Discord. Thanks for your help.
