### ISSUE TITLE
Problem to use it

### ISSUE THREAD

**Issue by youngZimbel** [CreativeMD/OnlinePictureFrame#58]
Hey i have load it in to forge on the right version(i also added little Tiles). Its crashing everytimes since i have installed Creative Core,Little Tiles and OnlinePictureFrame. i have hanging on the Latest crash Code.
![crash](https://user-images.githubusercontent.com/74208706/98585525-b5de1980-22c7-11eb-8d82-79ac8db8b950.png)

**Comment by youngZimbel** [comment]
[crash-2020-11-09_18.51.19-client.txt](https://github.com/CreativeMD/OnlinePictureFrame/files/5512752/crash-2020-11-09_18.51.19-client.txt)
here are the crash report

**Comment by youngZimbel** [comment]
[crash-2020-11-09_19.49.09-client.txt](https://github.com/CreativeMD/OnlinePictureFrame/files/5512789/crash-2020-11-09_19.49.09-client.txt)
thats the new one

**Comment by youngZimbel** [comment]
[crash-2020-11-09_20.22.49-client.txt](https://github.com/CreativeMD/OnlinePictureFrame/files/5512843/crash-2020-11-09_20.22.49-client.txt)
here the newest one

**Comment by CreativeMD** [comment]
Update to the newest version (you need the beta).
