### ISSUE TITLE
Possible rendering issue?

### ISSUE THREAD

**Issue by Dillonsmarty** [CreativeMD/OnlinePictureFrame#59]
My game crashes every time I look at a online picture frame. (Probably it could be something else.)
Here is the error.

The game crashed whilst rendering item
Error: java.lang.ClassCastException: com.creativemd.creativecore.client.rendering.RenderCubeObject cannot be cast to com.creativemd.creativecore.client.rendering.RenderBox
Exit Code: -1

**Comment by CreativeMD** [comment]
Use the newest version of OnlinePictureFrame, you need the beta.
