### ISSUE TITLE
Could not download image

### ISSUE THREAD

**Issue by LixYt** [CreativeMD/OnlinePictureFrame#62]
Hi there !

Still using your mod but having new issue (version : OnlinePicFrame_v1.4.40_mc1.12.2)

With this URL https://lix.yt/files/SW_RPG/minePaysageMontagne1.jpg, I got "Could not download image".
I did not found anything in debug nor latest log.

I'm hosting the file on my own server. If you found any wrong config on it, you may describe it and maybe I can also change that...

Regards,
Lix

**Comment by CreativeMD** [comment]
It works fine for me, maybe the whitelist is enabled?

**Comment by LixYt** [comment]
I tried to turn whitelist on and off, adding the domain in the whitelist too.... nothing :'(
don't know if it can help but I am hosting the server on Windows server 2012 R2.

I tried to host some on other free hoster service and it works fine, so I don't think there is any trouble with minecraft directory ACLs.

Also, I noticed something strange... when i remove the S of HTTPS (http://lix.yt/files/SW_RPG/minePaysageMontagne1.jpg), I get the following error (picture 4) : "Failed to parse GIF"...

![image](https://user-images.githubusercontent.com/45044873/103302598-53baae80-4a04-11eb-9517-1e65237052f1.png)
![image](https://user-images.githubusercontent.com/45044873/103302621-5f0dda00-4a04-11eb-856f-1dc317b9de44.png)
![image](https://user-images.githubusercontent.com/45044873/103302636-6503bb00-4a04-11eb-931e-98346a8c516b.png)
![image](https://user-images.githubusercontent.com/45044873/103303075-6386c280-4a05-11eb-9f45-7fc96c6a1448.png)

**Comment by LixYt** [comment]
POST SCRIPTUM : after editing the URL Rewrite rules on my server, i disabled the HTTPS rewirte rule for this directories and picture load in HTTP unsecured... (which is not the best solution but works)

**Comment by CreativeMD** [comment]
It's probably fixed in the newest version, sorry but you will have to update ... otherwise I can't do anything about it.

**Comment by LixYt** [comment]
unfortunately, v1.50 make the game crash...

[crash-2020-12-30_11.00.27-client.txt](https://github.com/CreativeMD/OnlinePictureFrame/files/5753816/crash-2020-12-30_11.00.27-client.txt)

**Comment by CreativeMD** [comment]
Because you have to update CreativeCore as well.
