### ISSUE TITLE
Warning: URL Whitelist not enabled

### ISSUE THREAD

**Issue by Raygonito** [CreativeMD/OnlinePictureFrame#65]
Hi!

I'm using this mod on a multiplayer minecraft server with Aternos.

It's on 1.12.2, however i can't seem to have place a URL because it says "Warning, URL Whitelist not enabled", Thanks!

**Comment by Raygonito** [comment]
Nvm, i found out that it does work my bad.

**Comment by Churgies** [comment]
Hi! Can you please explain to me what you did because I am having the same issue

**Comment by CreativeMD** [comment]
You can use the command /cmdconfig to enable or disable the whitelist. Most likely you can ignore this warning, it's just there for servers.

**Comment by massimoty** [comment]
hi!, how did you fix the problem? im in a singleplayer world

**Comment by CreativeMD** [comment]
There is no problem. The whitelist can be enabled, but does not have to be. If you want to enable it use the command /cmdconfig, otherwise just leave it.

**Comment by nIcksonMSPR** [comment]
> There is no problem. The whitelist can be enabled, but does not have to be. If you want to enable it use the command /cmdconfig, otherwise just leave it.

where do i type this command, i have the mod on and the command isnt a thing ?

**Comment by CreativeMD** [comment]
Just ingame ... the command only works if CreativeCore is installed on server side.

**Comment by Celivra** [comment]
After entering/cmdconfig, there is nothing to open the interface

**Comment by CreativeMD** [comment]
Sorry, but this mod is not supported anymore, please use LittleFrames instead.
