### ISSUE TITLE
Glitch when negative coords

### ISSUE THREAD

**Issue by lordlichi2006** [CreativeMD/OnlinePictureFrame#67]
So i put a negative coordinate -2 and the frame is not accesible anymore and cannot be broken 
![image](https://user-images.githubusercontent.com/81822578/113433841-38cf5000-93e0-11eb-8d4a-478a40ea7cda.png)

**Comment by CreativeMD** [comment]
Use the command /setblock <x> <y> <z> air to remove the frame. OnlinePictureFrame is also discontinued, but I will make sure this doesn't happen in LittleFrames.
