### ISSUE TITLE
Could not download image

### ISSUE THREAD

**Issue by onefraks** [CreativeMD/OnlinePictureFrame#68]
Hi, im playing in my world with Online Picture Frame v1.12.2 (v1.5.0-pre1) and all my images disappeared and the error "Could not download image" appeared

I use this images: 
https://i.ibb.co/02s12pS/wallpaper-aldea-mia.png
https://i.postimg.cc/0Q7mmyzF/construccion.png
https://i.ibb.co/hyQtwK4/construccion.png

Before they worked but now none of my images work.

Creative Core version: v1.10.60

**Comment by CreativeMD** [comment]
This mod has been discontinued, I recommend to use LittleFrames instead (https://www.curseforge.com/minecraft/mc-mods/littleframes)
