### ISSUE TITLE
image unloads when im far or when I restart the server

### ISSUE THREAD

**Issue by supreme-idiot** [CreativeMD/OnlinePictureFrame#70]
hi, im using Aternos server and whenever I get 5 chunks away from the frame or when I restart the server the image unloads and I have to click on the frame for it to load again, please help.

Thank u

**Comment by CreativeMD** [comment]
Sorry this mod has been discontinued and replaced by [LittleFrames](https://www.curseforge.com/minecraft/mc-mods/littleframes).
