### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by sprinkle-clould** [CreativeMD/OnlinePictureFrame#71]
Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
Contact their authors BEFORE contacting forge
I need help what should I do?

**Comment by sprinkle-clould** [comment]
oh nevermind problem fixed

**Comment by CreativeMD** [comment]
Rather use LittlePictureFrames.

**Comment by azdelux** [comment]
PLEASE HOW DID YOU FIXED IT

**Comment by azdelux** [comment]
ok nvm after few times retrying it worked (LittleFrames_WATERMEDIA_by_Blake_v1.1.4_mc1.12.2)
