### ISSUE TITLE
No tile drops?

### ISSUE THREAD

**Issue by reallydrained** [CreativeMD/OnlinePictureFrame#72]
When breaking the picture frame the tile never drops, I even have tried with silk touch and no luck. Is this intended? It's very annoying every time this happens in my survival server I have to /give myself or my buddy a new one every time.

MC version: 1.7.10
OPF version: [v1.0](https://www.curseforge.com/minecraft/mc-mods/onlinepictureframe/files/2486883)

**Comment by CreativeMD** [comment]
This mod has been discontinued and will not receive any support. Sorry.
