### ISSUE TITLE
Crash On Startup: NoClassDefFoundError

### ISSUE THREAD

**Issue by ChloeDawn** [CreativeMD/OnlinePictureFrame#9]
Crash from trying to load LittleTiles classes before checking if it is present.

**Mod version:** [1.4.2](https://minecraft.curseforge.com/projects/onlinepictureframe/files/2451984)
**Forge version:** [1.12-14.21.1.2413](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.1.2413/forge-1.12-14.21.1.2413-changelog.txt)

**Crash report:** [crash-2017-07-17_16.53.08-client](https://paste.ee/p/RAjyA)
**Relevant line in code:** [OPFrame.java#L69](https://github.com/CreativeMD/OnlinePictureFrame/blob/1.12/src/main/java/com/creativemd/opf/OPFrame.java#L69)

**Comment by CreativeMD** [comment]
Fixed it already, saw your discussion in discord.
